[package]
name = "matpatz/luaia"
version = "0.3.0"
description = "Luau Minifer written in Luau"
license = "GPL-3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Add dependencies here, e.g.:
# luau-polyfill = "github.com/roblox/luau-polyfill@0.1.0"

[dev-dependencies]
# Add dev dependencies here, e.g.:
# testez = "roblox/testez@0.4.1"
